version: '3.8'

services:
  # Telegram бот (продакшн)
  bot:
    build: .
    container_name: events_bot
    environment:
      # Обязательные переменные
      BOT_TOKEN: ${BOT_TOKEN}
      
      # База данных (внешняя)
      DATABASE_URL: ${DATABASE_URL}
      
      # Логирование
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}

      # Группа для модерации
      MODERATION_GROUP_ID: ${MODERATION_GROUP_ID}
      
      # Дополнительные настройки
      ENVIRONMENT: production
      DEBUG: "false"
    volumes:
      - uploads_data:/app/uploads:rw
    restart: unless-stopped

volumes:
  uploads_data:
    driver: local 